# This is the configuration file for your staging environment. The staging
# environment is meant to resemble the production environment as much as
# possible and may connect to production databases services and data. You use it
# for final testing before deploying the production server.
#
# Typically, you will want to route the traffic through a load balancer
# which adds SSL security through https. If you use Serverpod's standard
# Terraform scripts to deploy your server, all you need to change in
# this file is the examplepod.com domain name.

# Configuration for the main API server.
apiServer:
  port: 8080
  publicHost: 10.0.6.140
  publicPort: 443
  publicScheme: https

# Configuration for the Insights server.
insightsServer:
  port: 8081
  publicHost: 10.0.6.140
  publicPort: 443
  publicScheme: https

# Configuration for the web server.
webServer:
  port: 8082
  publicHost: 10.0.6.140
  publicPort: 443
  publicScheme: https

# This is the database setup for your servers.
database:
  host: 10.0.6.140
  port: 5432
  name: serverpod
  user: postgres

# This is the setup for Redis.
redis:
  enabled: false
  host: 10.0.6.140
  port: 6379
